package swim.sim.uwswarm.intelli.sense;

/**
 *
 * @author Sherif
 */
public enum Senses {
  
  MANY_NEIGHBORS,
  MODERATE_NEIGHBORS,
  FEW_NEIGHBORS,
  NO_NEIGHBORS,
  ONE_NEIGHBOR,
  NEIGHBOR_COLLISION,
  HEADING_AWAY_FROM_NEIGHBORS,
  HEADING_AS_NEIGHBORS,
  
  MANY_TARGETS,
  MODERATE_TARGETS,
  FEW_TARGETS,
  NO_TARGETS,
  TARGET_COLLISION,
  A_TARGET_NEARBY,
  
  FAR_FROM_OCEAN_FLOOR,
  CLOSE_TO_OCEAN_FLOOR,
  
  FAR_FROM_SURFACE,
  CLOSE_TO_SURFACE

}
